# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_caption_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='caption',
            name='backcolor',
            field=models.CharField(default='0,0,0', max_length=15),
        ),
        migrations.AlterField(
            model_name='caption',
            name='color',
            field=models.CharField(default='255,255,255', max_length=15),
        ),
    ]
